cookie:
  expiry_days: 30
  key: 244fd1bad4d7761921c6031eed578f8d
  name: test_cookie
credentials:
  usernames:
    shuto:
      email: shuto.work2828@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: shuto
      password: $2b$12$wDTd2pEsMGZc2zAmsCG0S.UQkdkPG4.GA0xxYR.DteSYBLOrsiT0a
    will:
      email: will@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: wil
      password: $2b$12$R5U.xvJj8ilVrVJcoA1Jh.ggAKuD8b6jg/y.y/E8OBfFwNmC4oY1i
pre-authorized:
  emails:
  - melsby@gmail.com
